# pylint: skip-file
# Generated by Django 2.2.17 on 2020-12-10 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=32, unique=True)),
                ('original_url', models.URLField(max_length=4096)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('external_url', models.URLField(max_length=4096)),
                ('metadata', models.TextField(default='{}', max_length=1048576)),
            ],
        ),
        migrations.CreateModel(
            name='LinkVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=4096, null=True)),
                ('metadata', models.TextField(default='{}', max_length=1048576)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='url_shortener.Link')),
            ],
        ),
    ]
