# pylint: skip-file
# Generated by Django 2.2.17 on 2020-12-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_apiclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='signing_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='apiclient',
            name='verification_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
