# pylint: skip-file
# Generated by Django 3.2.14 on 2023-12-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0004_auto_20220706_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='client_id',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
