# pylint: skip-file
# Generated by Django 3.2.14 on 2023-12-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0005_link_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=4096, null=True),
        ),
    ]
