# pylint: skip-file
# Generated by Django 3.2.25 on 2024-06-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0007_apiclient_query_window_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='last_click',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
