# pylint: skip-file
# Generated by Django 3.2.25 on 2024-06-03 15:40

from django.db import migrations, models
import url_shortener.models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0008_link_last_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclient',
            name='client_id',
            field=models.CharField(default=url_shortener.models.generate_client_id, max_length=64, unique=True, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='link',
            name='external_url',
            field=models.URLField(max_length=4096, verbose_name='External URL'),
        ),
        migrations.AlterField(
            model_name='link',
            name='original_url',
            field=models.URLField(max_length=4096, verbose_name='Original URL'),
        ),
    ]
