# pylint: skip-file
# Generated by Django 3.2.25 on 2024-06-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0009_auto_20240603_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='client_id',
            field=models.CharField(blank=True, db_index=True, max_length=4096, null=True, verbose_name='Client ID'),
        ),
    ]
