# pylint: skip-file
# Generated by Django 3.2.25 on 2024-06-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0010_alter_link_client_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiclient',
            options={'verbose_name': 'API Client'},
        ),
    ]
