# pylint: skip-file
# Generated by Django 3.2.25 on 2024-06-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0011_alter_apiclient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiclient',
            options={'verbose_name': 'API client'},
        ),
    ]
